# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class M3uDl < Formula
  desc "Browse Xtream IPTV catalogs and download into a Plex-compatible library."
  homepage "https://github.com/Thiritin/m3u-downloader"
  version "0.2.0"
  license "see LICENSE"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Thiritin/m3u-downloader/releases/download/v0.2.0/m3u-dl-v0.2.0-darwin-amd64.tar.gz"
      sha256 "edceef4b8133e9b4a9b1f8d74081fd9527f0a6cbd96b6639960fcdb18a5d1621"

      define_method(:install) do
        bin.install "m3u-dl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Thiritin/m3u-downloader/releases/download/v0.2.0/m3u-dl-v0.2.0-darwin-arm64.tar.gz"
      sha256 "c21d4d09db2991960840b3fa0503e9ab7ac58c55367f5c2915debfc0d36dcf71"

      define_method(:install) do
        bin.install "m3u-dl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Thiritin/m3u-downloader/releases/download/v0.2.0/m3u-dl-v0.2.0-linux-amd64.tar.gz"
      sha256 "ca5d8e25642a40d27ead336e06a247e99e5a43a24de13febc172430638379667"
      define_method(:install) do
        bin.install "m3u-dl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Thiritin/m3u-downloader/releases/download/v0.2.0/m3u-dl-v0.2.0-linux-arm64.tar.gz"
      sha256 "0763fe5e83654c2605c66a4f548c9181770ea5b764c76ba897f5dae044c46d62"
      define_method(:install) do
        bin.install "m3u-dl"
      end
    end
  end

  test do
    assert_match "m3u-dl", shell_output("#{bin}/m3u-dl --help", 2)
  end
end
