# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class M3uDl < Formula
  desc "Browse Xtream IPTV catalogs and download into a Plex-compatible library."
  homepage "https://github.com/Thiritin/m3u-downloader"
  version "0.1.1"
  license "see LICENSE"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Thiritin/m3u-downloader/releases/download/v0.1.1/m3u-dl-v0.1.1-darwin-amd64.tar.gz"
      sha256 "ccb7f0356a0943b828ca9ef5ca412436ed0686edf4e08d5cd16d0c28ac0e4d62"

      define_method(:install) do
        bin.install "m3u-dl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Thiritin/m3u-downloader/releases/download/v0.1.1/m3u-dl-v0.1.1-darwin-arm64.tar.gz"
      sha256 "e3d68ceecfb3074b662fddf2fa07e16d1fe1683a74c0adc40282684b1474de93"

      define_method(:install) do
        bin.install "m3u-dl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Thiritin/m3u-downloader/releases/download/v0.1.1/m3u-dl-v0.1.1-linux-amd64.tar.gz"
      sha256 "e297a479dc6653cefd043266c5d910614ca98a6f5f29e1875f77e3163e25bdbe"
      define_method(:install) do
        bin.install "m3u-dl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Thiritin/m3u-downloader/releases/download/v0.1.1/m3u-dl-v0.1.1-linux-arm64.tar.gz"
      sha256 "879cb6073f0b9eac169ab63d88e364e02f4b40e007dd942fd3b8c381de9af7aa"
      define_method(:install) do
        bin.install "m3u-dl"
      end
    end
  end

  test do
    assert_match "m3u-dl", shell_output("#{bin}/m3u-dl --help", 2)
  end
end
